export const container: string;
export const codeItems: string;
export const codeItem: string;
export const used: string;
export const unused: string;
export const detail: string;
export const title: string;
export const code: string;
export const restTime: string;
