"""
Django settings for xxj_EB project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import os
import server_config
from server_config import DEBUG, DATABASES

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f8m3e^7@#=*i%(=#^sgs(p=-l3@iy@d)=3036re$a+ca#c_!7g'

# SECURITY WARNING: don't run with debug turned on in production!localhost

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "192.168.2.5", "192.168.1.4", "www.kxshanghai.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'user',
    'product',
    'order',
    'image',
    'invite_code',
    'backend',
    'dinpay',
    'fe',
    '_wechatpub.django',
    'wechatpub'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rest_api.middleware.DisableCSRFCheck',
    'user.debug_middleware.DebugMiddleWare'
]

ROOT_URLCONF = 'xxj_EB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xxj_EB.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
AUTH_USER_MODEL = 'user.User'
MEDIA_ROOT = '/media/'

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = (
    '127.0.0.1:8001',
    '192.168.2.5:8001',
    'localhost:8001',
    'www.kxshanghai.com'
)

# 邮件配置
ADMINS = [("linyuchen", "lin.yu.chen@foxmail.com")]
EMAIL_HOST = "smtp.mxhichina.com"
EMAIL_PORT = 465
EMAIL_HOST_USER = "notify@linyuchen.net"
EMAIL_HOST_PASSWORD = "vXnhk8oGpbz"
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = SERVER_EMAIL = EMAIL_HOST_USER

# 微信公众号配置

WECHAT_PUB_SERVER_HTTP_HOST = server_config.HTTP_HOST
WECHAT_PUB_APPID = server_config.WECHAT_APPID
WECHAT_PUB_APPSECRET = server_config.WECHAT_APPSECRET
WECHAT_PUB_APPTOKEN = server_config.WECHAT_APP_TOKEN

WECHAT_PUB_QRCODE_URL = server_config.WECHAT_QRCODE_URL  # 公众号二维码

WECHAT_PAY_MCHID = server_config.WECHAT_PAY_MCHID
WECHAT_PAY_KEY = server_config.WECHAT_PAY_KEY
